// ============================================================
// lib/sample-recipes.ts - サンプルレシピ（2026-09-30新設）
// ============================================================
// このファイルは自動生成（元データ：日本食品標準成分表2020年版（八訂）の原本xlsx）。
// 材料は食品番号（nutritionId）で食品成分表と紐づける。本番DBにその食品番号が無い場合に
// 備えて、100gあたりの栄養値も同梱し、その場合は手入力値として登録する（lib/sample-import.ts）。
// 炭水化物は食品表示基準に合わせ「炭水化物」列（CHOCDF-）の値を入れている。

export type SampleIngredientDef = {
  name: string;            // 食材マスタ名（利用者の食材マスタに同名があればそれを再利用）
  labelName: string;       // ラベル表示用の一般名
  foodId: number | null;   // 食品番号（nutrition_data.id）
  allergens: string[];
  isAdditive: boolean;
  alwaysHideFromLabel: boolean;
  per100g: { energyKcal: number|null; protein: number|null; fat: number|null; carbohydrate: number|null; sodium: number|null; saltEquivalent: number|null; dietaryFiber: number|null; cholesterol: number|null };
};

export type SampleRecipeDef = {
  key: string; genre: string; name: string; unitCount: number;
  shelfLifeDays: number; shelfLifeType: "BEST_BEFORE" | "USE_BY";
  contentAmount: string; storageMethod: string; originCountry?: string;
  ingredients: Array<{ ing: string; amount: number }>;
  bakingConditions: Array<{ topHeat?: number; bottomHeat?: number; timeMin?: number; steam?: "ON" | "OFF" }>;
  steps: string[];
};

export const SAMPLE_GENRES = ["焼き菓子", "パン", "ケーキ・生菓子", "惣菜・和菓子・ジャム"] as const;

export const SAMPLE_INGREDIENTS: Record<string, SampleIngredientDef> = {
  hakuriki: { name: "小麦粉（薄力粉）", labelName: "小麦粉", foodId: 1015, allergens: ["小麦"], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 349.0, "protein": 8.3, "fat": 1.5, "carbohydrate": 75.8, "sodium": 0.001, "saltEquivalent": 0.0, "dietaryFiber": 2.5, "cholesterol": 0.0} },
  kyoriki: { name: "小麦粉（強力粉）", labelName: "小麦粉", foodId: 1020, allergens: ["小麦"], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 337.0, "protein": 11.8, "fat": 1.5, "carbohydrate": 71.7, "sodium": 0.001, "saltEquivalent": 0.0, "dietaryFiber": 2.7, "cholesterol": 0.0} },
  butter: { name: "バター（食塩不使用）", labelName: "バター", foodId: 14018, allergens: ["乳"], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 720.0, "protein": 0.5, "fat": 83.0, "carbohydrate": 0.2, "sodium": 11.0, "saltEquivalent": 0.0, "dietaryFiber": 0.0, "cholesterol": 220.0} },
  egg: { name: "鶏卵", labelName: "鶏卵", foodId: 12004, allergens: ["卵"], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 142.0, "protein": 12.2, "fat": 10.2, "carbohydrate": 0.4, "sodium": 140.0, "saltEquivalent": 0.4, "dietaryFiber": 0.0, "cholesterol": 370.0} },
  jouhakutou: { name: "上白糖", labelName: "砂糖", foodId: 3003, allergens: [], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 391.0, "protein": 0.0, "fat": 0.0, "carbohydrate": 99.3, "sodium": 1.0, "saltEquivalent": 0.0, "dietaryFiber": 0.0, "cholesterol": 0.0} },
  granulated: { name: "グラニュー糖", labelName: "砂糖", foodId: 3005, allergens: [], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 393.0, "protein": 0.0, "fat": 0.0, "carbohydrate": 100.0, "sodium": 0.001, "saltEquivalent": 0.0, "dietaryFiber": 0.0, "cholesterol": 0.0} },
  milk: { name: "牛乳", labelName: "牛乳", foodId: 13003, allergens: ["乳"], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 61.0, "protein": 3.3, "fat": 3.8, "carbohydrate": 4.8, "sodium": 41.0, "saltEquivalent": 0.1, "dietaryFiber": 0.0, "cholesterol": 12.0} },
  cream: { name: "生クリーム（乳脂肪）", labelName: "クリーム（乳製品）", foodId: 13014, allergens: ["乳"], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 404.0, "protein": 1.9, "fat": 43.0, "carbohydrate": 6.5, "sodium": 43.0, "saltEquivalent": 0.1, "dietaryFiber": 0.0, "cholesterol": 64.0} },
  creamcheese: { name: "クリームチーズ", labelName: "クリームチーズ", foodId: 13035, allergens: ["乳"], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 313.0, "protein": 8.2, "fat": 33.0, "carbohydrate": 2.3, "sodium": 260.0, "saltEquivalent": 0.7, "dietaryFiber": 0.0, "cholesterol": 99.0} },
  bp: { name: "膨張剤（ベーキングパウダー）", labelName: "膨張剤", foodId: 17084, allergens: [], isAdditive: true, alwaysHideFromLabel: false, per100g: {"energyKcal": 149.904, "protein": 0.001, "fat": 1.2, "carbohydrate": 29.0, "sodium": 6800.0, "saltEquivalent": 17.3, "dietaryFiber": null, "cholesterol": 0.0} },
  yeast: { name: "イースト（ドライ）", labelName: "イースト", foodId: 17083, allergens: [], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 307.0, "protein": 37.1, "fat": 6.8, "carbohydrate": 43.1, "sodium": 120.0, "saltEquivalent": 0.3, "dietaryFiber": 32.6, "cholesterol": 0.0} },
  salt: { name: "食塩", labelName: "食塩", foodId: 17012, allergens: [], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 0.0, "protein": 0.0, "fat": 0.0, "carbohydrate": 0.0, "sodium": 39000.0, "saltEquivalent": 99.1, "dietaryFiber": 0.0, "cholesterol": 0.0} },
  honey: { name: "はちみつ", labelName: "はちみつ", foodId: 3022, allergens: [], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 329.0, "protein": 0.3, "fat": 0.001, "carbohydrate": 81.9, "sodium": 2.0, "saltEquivalent": 0.0, "dietaryFiber": 0.0, "cholesterol": 0.0} },
  strawberry: { name: "いちご", labelName: "いちご", foodId: 7012, allergens: [], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 31.0, "protein": 0.9, "fat": 0.1, "carbohydrate": 8.5, "sodium": 0.001, "saltEquivalent": 0.0, "dietaryFiber": 1.4, "cholesterol": 0.0} },
  lemon: { name: "レモン果汁", labelName: "レモン果汁", foodId: 7156, allergens: [], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 24.0, "protein": 0.4, "fat": 0.2, "carbohydrate": 8.6, "sodium": 2.0, "saltEquivalent": 0.0, "dietaryFiber": 0.001, "cholesterol": 0.0} },
  skim: { name: "脱脂粉乳", labelName: "脱脂粉乳", foodId: 13010, allergens: ["乳"], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 354.0, "protein": 34.0, "fat": 1.0, "carbohydrate": 53.3, "sodium": 570.0, "saltEquivalent": 1.4, "dietaryFiber": 0.0, "cholesterol": 25.0} },
  shiratama: { name: "白玉粉", labelName: "白玉粉", foodId: 1120, allergens: [], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 347.0, "protein": 6.3, "fat": 1.0, "carbohydrate": 80.0, "sodium": 2.0, "saltEquivalent": 0.0, "dietaryFiber": 0.5, "cholesterol": 0.0} },
  koshian: { name: "こしあん", labelName: "こしあん", foodId: 4101, allergens: [], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 239.0, "protein": 5.6, "fat": 0.3, "carbohydrate": 58.8, "sodium": 2.0, "saltEquivalent": 0.0, "dietaryFiber": 3.9, "cholesterol": 0.0} },
  soysauce: { name: "しょうゆ", labelName: "しょうゆ", foodId: 17007, allergens: ["小麦", "大豆"], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 77.0, "protein": 7.7, "fat": 0.0, "carbohydrate": 7.9, "sodium": 5700.0, "saltEquivalent": 14.5, "dietaryFiber": 0.001, "cholesterol": 0.0} },
  sake: { name: "清酒", labelName: "清酒", foodId: 16001, allergens: [], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 107.0, "protein": 0.4, "fat": 0.001, "carbohydrate": 4.9, "sodium": 2.0, "saltEquivalent": 0.0, "dietaryFiber": 0.0, "cholesterol": 0.0} },
  garlic: { name: "にんにく", labelName: "にんにく", foodId: 6223, allergens: [], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 129.0, "protein": 6.4, "fat": 0.9, "carbohydrate": 27.5, "sodium": 8.0, "saltEquivalent": 0.001, "dietaryFiber": 6.2, "cholesterol": 0.0} },
  ginger: { name: "しょうが", labelName: "しょうが", foodId: 6103, allergens: [], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 28.0, "protein": 0.9, "fat": 0.3, "carbohydrate": 6.6, "sodium": 6.0, "saltEquivalent": 0.0, "dietaryFiber": 2.1, "cholesterol": 0.0} },
  potatostarch: { name: "でん粉（片栗粉）", labelName: "でん粉", foodId: 2034, allergens: [], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 338.0, "protein": 0.1, "fat": 0.1, "carbohydrate": 81.6, "sodium": 2.0, "saltEquivalent": 0.0, "dietaryFiber": 0.0, "cholesterol": 0.0} },
  oil: { name: "植物油", labelName: "植物油", foodId: 14006, allergens: [], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 886.0, "protein": 0.0, "fat": 100.0, "carbohydrate": 0.0, "sodium": 0.0, "saltEquivalent": 0.0, "dietaryFiber": 0.0, "cholesterol": 2.0} },
  chicken: { name: "鶏肉（もも）", labelName: "鶏肉", foodId: 11221, allergens: ["鶏肉"], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 190.0, "protein": 16.6, "fat": 14.2, "carbohydrate": 0.0, "sodium": 62.0, "saltEquivalent": 0.2, "dietaryFiber": 0.0, "cholesterol": 89.0} },
  cornstarch: { name: "コーンスターチ", labelName: "コーンスターチ", foodId: 2035, allergens: [], isAdditive: false, alwaysHideFromLabel: false, per100g: {"energyKcal": 363.0, "protein": 0.1, "fat": 0.7, "carbohydrate": 86.3, "sodium": 1.0, "saltEquivalent": 0.0, "dietaryFiber": 0.0, "cholesterol": 0.0} },
  water: { name: "水", labelName: "水", foodId: null, allergens: [], isAdditive: false, alwaysHideFromLabel: true, per100g: {"energyKcal": 0, "protein": 0, "fat": 0, "carbohydrate": 0, "sodium": 0, "saltEquivalent": 0, "dietaryFiber": 0, "cholesterol": 0} },
};

export const SAMPLE_RECIPES: SampleRecipeDef[] = [
  {"key": "s01", "genre": "焼き菓子", "name": "【サンプル】バタークッキー", "unitCount": 20, "shelfLifeDays": 30, "shelfLifeType": "BEST_BEFORE", "contentAmount": "1枚", "storageMethod": "直射日光・高温多湿を避けて保存してください。", "ingredients": [{"ing": "hakuriki", "amount": 200}, {"ing": "butter", "amount": 120}, {"ing": "jouhakutou", "amount": 80}, {"ing": "egg", "amount": 30}], "bakingConditions": [{"topHeat": 170, "bottomHeat": 170, "timeMin": 15}], "steps": ["バターを室温に戻し、砂糖を加えて白っぽくなるまですり混ぜる。", "溶き卵を少しずつ加えて混ぜる。", "薄力粉をふるい入れ、さっくり混ぜて生地をまとめる。", "冷蔵庫で30分休ませ、5mm厚にのばして型で抜く。", "170℃のオーブンで約15分焼く。"]},
  {"key": "s02", "genre": "焼き菓子", "name": "【サンプル】マドレーヌ", "unitCount": 10, "shelfLifeDays": 14, "shelfLifeType": "BEST_BEFORE", "contentAmount": "1個", "storageMethod": "直射日光・高温多湿を避けて保存してください。", "ingredients": [{"ing": "hakuriki", "amount": 100}, {"ing": "egg", "amount": 100}, {"ing": "granulated", "amount": 90}, {"ing": "butter", "amount": 100}, {"ing": "honey", "amount": 15}, {"ing": "bp", "amount": 3}], "bakingConditions": [{"topHeat": 180, "bottomHeat": 180, "timeMin": 12}], "steps": ["卵とグラニュー糖、はちみつをすり混ぜる。", "薄力粉とベーキングパウダーをふるい入れて混ぜる。", "溶かしバターを加えて混ぜ、1時間休ませる。", "型に流し、180℃で約12分焼く。"]},
  {"key": "s03", "genre": "焼き菓子", "name": "【サンプル】パウンドケーキ", "unitCount": 8, "shelfLifeDays": 10, "shelfLifeType": "BEST_BEFORE", "contentAmount": "1切れ", "storageMethod": "直射日光・高温多湿を避けて保存してください。", "ingredients": [{"ing": "hakuriki", "amount": 120}, {"ing": "butter", "amount": 120}, {"ing": "granulated", "amount": 120}, {"ing": "egg", "amount": 120}, {"ing": "bp", "amount": 2}], "bakingConditions": [{"topHeat": 170, "bottomHeat": 170, "timeMin": 45}], "steps": ["バターとグラニュー糖をすり混ぜる。", "溶き卵を少しずつ加えて乳化させる。", "粉類をふるい入れて混ぜ、型に流す。", "170℃で約45分焼き、8等分する。"]},
  {"key": "s04", "genre": "パン", "name": "【サンプル】食パン", "unitCount": 1, "shelfLifeDays": 3, "shelfLifeType": "BEST_BEFORE", "contentAmount": "1斤", "storageMethod": "直射日光・高温多湿を避けて保存してください。", "ingredients": [{"ing": "kyoriki", "amount": 250}, {"ing": "water", "amount": 175}, {"ing": "jouhakutou", "amount": 15}, {"ing": "butter", "amount": 15}, {"ing": "skim", "amount": 8}, {"ing": "salt", "amount": 5}, {"ing": "yeast", "amount": 3}], "bakingConditions": [{"topHeat": 200, "bottomHeat": 200, "timeMin": 30}], "steps": ["バター以外の材料をこね、まとまったらバターを加えてさらにこねる。", "一次発酵（約60分）。", "分割・丸め、ベンチタイム15分。", "成形して型に入れ、二次発酵（約50分）。", "200℃で約30分焼く。"]},
  {"key": "s05", "genre": "パン", "name": "【サンプル】バターロール", "unitCount": 10, "shelfLifeDays": 3, "shelfLifeType": "BEST_BEFORE", "contentAmount": "1個", "storageMethod": "直射日光・高温多湿を避けて保存してください。", "ingredients": [{"ing": "kyoriki", "amount": 250}, {"ing": "water", "amount": 80}, {"ing": "milk", "amount": 70}, {"ing": "butter", "amount": 40}, {"ing": "jouhakutou", "amount": 30}, {"ing": "egg", "amount": 25}, {"ing": "salt", "amount": 4}, {"ing": "yeast", "amount": 4}], "bakingConditions": [{"topHeat": 190, "bottomHeat": 190, "timeMin": 12}], "steps": ["材料をこね、一次発酵（約50分）。", "10分割して丸め、ベンチタイム15分。", "ロール形に成形し、二次発酵（約40分）。", "溶き卵（分量外）を塗り、190℃で約12分焼く。"]},
  {"key": "s06", "genre": "パン", "name": "【サンプル】あんぱん", "unitCount": 8, "shelfLifeDays": 3, "shelfLifeType": "BEST_BEFORE", "contentAmount": "1個", "storageMethod": "直射日光・高温多湿を避けて保存してください。", "ingredients": [{"ing": "koshian", "amount": 320}, {"ing": "kyoriki", "amount": 200}, {"ing": "milk", "amount": 60}, {"ing": "water", "amount": 50}, {"ing": "jouhakutou", "amount": 25}, {"ing": "butter", "amount": 20}, {"ing": "egg", "amount": 20}, {"ing": "salt", "amount": 3}, {"ing": "yeast", "amount": 4}], "bakingConditions": [{"topHeat": 190, "bottomHeat": 190, "timeMin": 13}], "steps": ["生地をこね、一次発酵（約50分）。", "8分割して丸め、こしあん40gずつを包む。", "二次発酵（約40分）後、190℃で約13分焼く。"]},
  {"key": "s07", "genre": "ケーキ・生菓子", "name": "【サンプル】いちごのショートケーキ", "unitCount": 6, "shelfLifeDays": 1, "shelfLifeType": "USE_BY", "contentAmount": "1カット", "storageMethod": "要冷蔵（10℃以下）", "ingredients": [{"ing": "cream", "amount": 300}, {"ing": "strawberry", "amount": 250}, {"ing": "egg", "amount": 150}, {"ing": "granulated", "amount": 114}, {"ing": "hakuriki", "amount": 90}, {"ing": "butter", "amount": 15}, {"ing": "milk", "amount": 15}], "bakingConditions": [{"topHeat": 170, "bottomHeat": 170, "timeMin": 30}], "steps": ["卵とグラニュー糖90gを湯せんで温めながら泡立てる。", "薄力粉をふるい入れ、溶かしバターと牛乳を加えて混ぜる。", "15cm型に流し、170℃で約30分焼く。", "生クリームにグラニュー糖24gを加えて泡立てる。", "スポンジを2枚にスライスし、いちごとクリームでデコレーションして6等分する。"]},
  {"key": "s08", "genre": "ケーキ・生菓子", "name": "【サンプル】ベイクドチーズケーキ", "unitCount": 8, "shelfLifeDays": 3, "shelfLifeType": "USE_BY", "contentAmount": "1カット", "storageMethod": "要冷蔵（10℃以下）", "ingredients": [{"ing": "creamcheese", "amount": 200}, {"ing": "egg", "amount": 100}, {"ing": "cream", "amount": 100}, {"ing": "granulated", "amount": 60}, {"ing": "hakuriki", "amount": 15}, {"ing": "lemon", "amount": 10}], "bakingConditions": [{"topHeat": 160, "bottomHeat": 160, "timeMin": 45}], "steps": ["クリームチーズを柔らかく練り、グラニュー糖を加えて混ぜる。", "卵、生クリーム、レモン果汁の順に加えて混ぜる。", "薄力粉をふるい入れて混ぜ、型に流す。", "160℃で約45分焼き、冷蔵庫で冷やして8等分する。"]},
  {"key": "s09", "genre": "ケーキ・生菓子", "name": "【サンプル】カスタードプリン", "unitCount": 6, "shelfLifeDays": 2, "shelfLifeType": "USE_BY", "contentAmount": "1個", "storageMethod": "要冷蔵（10℃以下）", "ingredients": [{"ing": "milk", "amount": 300}, {"ing": "egg", "amount": 150}, {"ing": "granulated", "amount": 110}, {"ing": "water", "amount": 15}], "bakingConditions": [{"topHeat": 150, "bottomHeat": 150, "timeMin": 35, "steam": "ON"}], "steps": ["グラニュー糖40gと水でカラメルを作り、容器に流す。", "牛乳とグラニュー糖70gを温め、溶き卵に少しずつ加えて混ぜ、こす。", "容器に流し、150℃で約35分蒸し焼きにする。", "粗熱を取って冷蔵庫で冷やす。"]},
  {"key": "s10", "genre": "惣菜・和菓子・ジャム", "name": "【サンプル】鶏の唐揚げ", "unitCount": 4, "shelfLifeDays": 1, "shelfLifeType": "USE_BY", "contentAmount": "1パック（約200g）", "storageMethod": "要冷蔵（10℃以下）", "originCountry": "国産", "ingredients": [{"ing": "chicken", "amount": 800}, {"ing": "potatostarch", "amount": 60}, {"ing": "oil", "amount": 50}, {"ing": "soysauce", "amount": 40}, {"ing": "sake", "amount": 30}, {"ing": "garlic", "amount": 10}, {"ing": "ginger", "amount": 10}], "bakingConditions": [], "steps": ["鶏肉を一口大に切り、しょうゆ・酒・すりおろしたにんにくとしょうがで30分漬ける。", "片栗粉をまぶし、170℃の油で約4分揚げる。", "一度取り出して休ませ、190℃で1分二度揚げする。", "4パックに分けて詰める（油は吸油分の目安として計上）。"]},
  {"key": "s11", "genre": "惣菜・和菓子・ジャム", "name": "【サンプル】大福（こしあん）", "unitCount": 8, "shelfLifeDays": 2, "shelfLifeType": "USE_BY", "contentAmount": "1個", "storageMethod": "直射日光・高温多湿を避けて保存してください。", "ingredients": [{"ing": "koshian", "amount": 240}, {"ing": "water", "amount": 180}, {"ing": "shiratama", "amount": 120}, {"ing": "jouhakutou", "amount": 40}, {"ing": "cornstarch", "amount": 15}], "bakingConditions": [], "steps": ["こしあんを30gずつ丸めておく。", "白玉粉に水を少しずつ加えて溶き、砂糖を加える。", "電子レンジで加熱し、途中で混ぜながら餅状にする。", "打ち粉（コーンスターチ）をした台に取り、8等分してあんを包む。"]},
  {"key": "s12", "genre": "惣菜・和菓子・ジャム", "name": "【サンプル】いちごジャム", "unitCount": 4, "shelfLifeDays": 180, "shelfLifeType": "BEST_BEFORE", "contentAmount": "150g", "storageMethod": "直射日光・高温多湿を避けて保存してください。開封後は要冷蔵。", "ingredients": [{"ing": "strawberry", "amount": 500}, {"ing": "granulated", "amount": 250}, {"ing": "lemon", "amount": 15}], "bakingConditions": [], "steps": ["いちごのへたを取り、グラニュー糖をまぶして1時間置く。", "中火にかけ、あくを取りながら煮詰める。", "レモン果汁を加えてとろみがつくまで煮る。", "煮沸消毒した瓶に熱いうちに詰め、脱気する。"]},
];
